'use strict';

const { addDays, startOfDay } = require('../utils/helpers');

/** Demo passwords — documented in the README, changed by the user after login. */
const DEMO_PASSWORD = 'Sample@123';

const users = {
  admin: {
    name: 'Amara Okafor',
    email: 'admin@eventsphere.io',
    role: 'admin',
    phone: '+1 415 555 0101',
    organization: 'EventSphere Events Group',
    jobTitle: 'Head of Expos',
    city: 'San Francisco',
    country: 'United States',
    bio: 'Programme director for large-scale technology and industry expos.',
    interests: ['technology', 'innovation', 'logistics'],
  },
  coAdmin: {
    name: 'Daniel Reyes',
    email: 'operations@eventsphere.io',
    role: 'admin',
    phone: '+1 415 555 0199',
    organization: 'EventSphere Events Group',
    jobTitle: 'Operations Lead',
    city: 'San Francisco',
    country: 'United States',
  },
  exhibitors: [
    {
      user: {
        name: 'Priya Raman',
        email: 'exhibitor@nexarobotics.io',
        role: 'exhibitor',
        phone: '+1 408 555 0110',
        organization: 'Nexa Robotics',
        jobTitle: 'Head of Partnerships',
        city: 'San Jose',
        country: 'United States',
      },
      profile: {
        companyName: 'Nexa Robotics',
        tagline: 'Collaborative robots for smart factories and labs',
        description:
          'Nexa Robotics builds collaborative robotic arms and autonomous mobile robots for manufacturing, laboratories and logistics. Our platforms ship with an open SDK, vision-based safety systems and a cloud fleet manager used by more than 300 plants worldwide.',
        categories: ['technology', 'manufacturing', 'software'],
        website: 'https://nexarobotics.example.com',
        foundedYear: 2016,
        employeeCount: '250-500',
        contact: { email: 'hello@nexarobotics.io', phone: '+1 408 555 0110', address: '1200 Innovation Drive', city: 'San Jose', country: 'United States' },
        socials: { linkedin: 'https://linkedin.com/company/nexarobotics', twitter: '@nexarobotics' },
        verificationStatus: 'verified',
      },
      products: [
        {
          name: 'NexaArm C6 Collaborative Robot',
          description: 'Six-axis collaborative arm with 12 kg payload, vision-guided pick and place, and a 0.02 mm repeatability rating.',
          category: 'robotics',
          price: 24500,
          currency: 'USD',
          tags: ['robotics', 'automation', 'cobot'],
          isFeatured: true,
        },
        {
          name: 'NexaFleet AMR',
          description: 'Autonomous mobile robot with 500 kg payload, SLAM navigation and fleet orchestration through the NexaCloud dashboard.',
          category: 'robotics',
          price: 31000,
          currency: 'USD',
          tags: ['amr', 'logistics', 'warehouse'],
          isFeatured: true,
        },
        {
          name: 'NexaVision QA',
          description: 'Machine-vision quality inspection service with defect detection models trained on your production line.',
          category: 'software',
          kind: 'service',
          price: 4900,
          currency: 'USD',
          tags: ['machine vision', 'quality', 'ai'],
        },
      ],
      staff: [
        { name: 'Marcus Lee', role: 'Solutions Engineer', email: 'marcus.lee@nexarobotics.io', phone: '+1 408 555 0111' },
        { name: 'Sofia Alvarez', role: 'Sales Director', email: 'sofia.alvarez@nexarobotics.io', phone: '+1 408 555 0112' },
      ],
      documents: [{ title: 'Company registration certificate', type: 'registration', status: 'approved' }],
    },
    {
      user: {
        name: 'Kenji Watanabe',
        email: 'exhibitor@voltedge.io',
        role: 'exhibitor',
        phone: '+81 3 5555 0142',
        organization: 'VoltEdge Electronics',
        jobTitle: 'Regional Sales Manager',
        city: 'Tokyo',
        country: 'Japan',
      },
      profile: {
        companyName: 'VoltEdge Electronics',
        tagline: 'Power electronics and embedded sensing for industrial IoT',
        description:
          'VoltEdge designs power management ICs, industrial sensors and edge gateways for energy, automotive and smart-building customers. Our portfolio covers wide-bandgap semiconductors, battery management and predictive maintenance sensing.',
        categories: ['electronics', 'technology', 'energy'],
        website: 'https://voltedge.example.com',
        foundedYear: 2009,
        employeeCount: '1000+',
        contact: { email: 'sales@voltedge.io', phone: '+81 3 5555 0142', address: '3-14 Shibaura', city: 'Tokyo', country: 'Japan' },
        socials: { linkedin: 'https://linkedin.com/company/voltedge' },
        verificationStatus: 'verified',
      },
      products: [
        {
          name: 'VE-G7 Industrial IoT Gateway',
          description: 'Modbus, MQTT and OPC-UA gateway with edge analytics, DIN-rail mounting and 4G/LTE fallback.',
          category: 'electronics',
          price: 1290,
          currency: 'USD',
          tags: ['iot', 'gateway', 'electronics'],
          isFeatured: true,
        },
        {
          name: 'VoltSense Vibration Sensor',
          description: 'Wireless tri-axial vibration and temperature sensor with five-year battery life for predictive maintenance.',
          category: 'electronics',
          price: 240,
          currency: 'USD',
          tags: ['sensors', 'predictive maintenance', 'electronics'],
        },
        {
          name: 'GaN Power Module 1200V',
          description: 'High-efficiency gallium-nitride power module for EV chargers and solar inverters.',
          category: 'energy',
          price: 310,
          currency: 'USD',
          tags: ['power', 'gan', 'ev'],
        },
      ],
      staff: [{ name: 'Hana Sato', role: 'Field Application Engineer', email: 'hana.sato@voltedge.io' }],
      documents: [{ title: 'Product compliance certificates (CE, UL)', type: 'compliance', status: 'approved' }],
    },
    {
      user: {
        name: 'Dr. Elena Fischer',
        email: 'exhibitor@medicore.health',
        role: 'exhibitor',
        phone: '+49 30 5555 0173',
        organization: 'MediCore Health Systems',
        jobTitle: 'Chief Commercial Officer',
        city: 'Berlin',
        country: 'Germany',
      },
      profile: {
        companyName: 'MediCore Health Systems',
        tagline: 'Connected diagnostics for clinics and home care',
        description:
          'MediCore develops connected diagnostic devices, remote patient monitoring platforms and clinical decision-support software used by hospitals in 22 countries. We focus on interoperability with HL7 FHIR and on data privacy by design.',
        categories: ['healthcare', 'software', 'technology'],
        website: 'https://medicore.example.com',
        foundedYear: 2012,
        employeeCount: '500-1000',
        contact: { email: 'partners@medicore.health', phone: '+49 30 5555 0173', address: 'Friedrichstraße 100', city: 'Berlin', country: 'Germany' },
        socials: { linkedin: 'https://linkedin.com/company/medicore-health' },
        verificationStatus: 'verified',
      },
      products: [
        {
          name: 'MediCore VitalLink Monitor',
          description: 'Multi-parameter patient monitor with 12-lead ECG, SpO2 and secure cloud streaming over HL7 FHIR.',
          category: 'healthcare',
          price: 8900,
          currency: 'USD',
          tags: ['diagnostics', 'monitoring', 'healthcare'],
          isFeatured: true,
        },
        {
          name: 'HomeCare Remote Platform',
          description: 'Remote patient monitoring SaaS with clinician dashboards, escalation rules and reimbursement reporting.',
          category: 'software',
          kind: 'service',
          price: 75,
          currency: 'USD',
          tags: ['saas', 'telehealth', 'healthcare'],
        },
      ],
      staff: [{ name: 'Jonas Weber', role: 'Clinical Product Lead', email: 'jonas.weber@medicore.health' }],
      documents: [{ title: 'ISO 13485 quality certificate', type: 'compliance', status: 'pending' }],
    },
    {
      user: {
        name: 'Chidi Nwosu',
        email: 'exhibitor@blueorbit.dev',
        role: 'exhibitor',
        phone: '+44 20 5555 0121',
        organization: 'BlueOrbit Software',
        jobTitle: 'Founder & CEO',
        city: 'London',
        country: 'United Kingdom',
      },
      profile: {
        companyName: 'BlueOrbit Software',
        tagline: 'Analytics and automation for event-driven businesses',
        description:
          'BlueOrbit builds streaming analytics and workflow automation products for logistics, retail and financial services teams. Our platform ingests millions of events per minute and ships with a no-code orchestration builder.',
        categories: ['software', 'technology', 'finance'],
        website: 'https://blueorbit.example.com',
        foundedYear: 2019,
        employeeCount: '50-100',
        contact: { email: 'team@blueorbit.dev', phone: '+44 20 5555 0121', address: '20 Ropemaker Street', city: 'London', country: 'United Kingdom' },
        socials: { linkedin: 'https://linkedin.com/company/blueorbit', website: 'https://blueorbit.example.com' },
        verificationStatus: 'pending',
      },
      products: [
        {
          name: 'OrbitStream Analytics',
          description: 'Real-time event streaming analytics with SQL-like windowing, alerting and prebuilt logistics dashboards.',
          category: 'software',
          price: 1450,
          currency: 'USD',
          tags: ['analytics', 'streaming', 'saas'],
          isFeatured: true,
        },
        {
          name: 'OrbitFlow Automation',
          description: 'No-code workflow automation with 200+ connectors, retries and human-in-the-loop approvals.',
          category: 'software',
          price: 890,
          currency: 'USD',
          tags: ['automation', 'workflow', 'software'],
        },
      ],
      staff: [{ name: 'Amelia Clarke', role: 'Solutions Architect', email: 'amelia@blueorbit.dev' }],
    },
  ],
  attendees: [
    {
      name: 'Jordan Blake',
      email: 'attendee@example.com',
      role: 'attendee',
      phone: '+1 212 555 0180',
      organization: 'Harborview Manufacturing',
      jobTitle: 'Plant Operations Manager',
      city: 'New York',
      country: 'United States',
      interests: ['robotics', 'automation', 'manufacturing'],
    },
    {
      name: 'Aisha Bello',
      email: 'aisha.bello@example.com',
      role: 'attendee',
      organization: 'Northwind Logistics',
      jobTitle: 'Supply Chain Analyst',
      city: 'Chicago',
      country: 'United States',
      interests: ['logistics', 'analytics', 'energy'],
    },
    {
      name: 'Tomás Ferreira',
      email: 'tomas.ferreira@example.com',
      role: 'attendee',
      organization: 'Lisbon General Hospital',
      jobTitle: 'Biomedical Engineer',
      city: 'Lisbon',
      country: 'Portugal',
      interests: ['healthcare', 'diagnostics'],
    },
    {
      name: 'Mei Lin',
      email: 'mei.lin@example.com',
      role: 'attendee',
      organization: 'Solaris Energy',
      jobTitle: 'Grid Solutions Engineer',
      city: 'Singapore',
      country: 'Singapore',
      interests: ['energy', 'electronics', 'sustainability'],
    },
    {
      name: 'Lucas Moreau',
      email: 'lucas.moreau@example.com',
      role: 'attendee',
      organization: 'Atelier Numérique',
      jobTitle: 'Product Designer',
      city: 'Paris',
      country: 'France',
      interests: ['design', 'software'],
    },
    {
      name: 'Sara Haddad',
      email: 'sara.haddad@example.com',
      role: 'attendee',
      organization: 'Cedar Financial',
      jobTitle: 'Risk Technology Lead',
      city: 'Dubai',
      country: 'United Arab Emirates',
      interests: ['finance', 'automation'],
    },
  ],
  speakers: [
    {
      name: 'Dr. Nadia Petrova',
      title: 'Chief Scientist',
      organization: 'Institute for Applied Robotics',
      bio: 'Nadia leads research on human-robot collaboration and safety standards for collaborative robots in shared workspaces.',
      expertise: ['robotics', 'safety', 'automation'],
      isFeatured: true,
      socials: { linkedin: 'https://linkedin.com/in/nadiapetrova' },
    },
    {
      name: 'Samuel Osei',
      title: 'VP of Engineering',
      organization: 'VoltEdge Electronics',
      bio: 'Samuel has shipped power electronics for EV charging and grid-scale storage across three continents.',
      expertise: ['power electronics', 'energy', 'embedded'],
      isFeatured: true,
    },
    {
      name: 'Dr. Ingrid Hauser',
      title: 'Director of Clinical Informatics',
      organization: 'MediCore Health Systems',
      bio: 'Ingrid works on interoperability standards and privacy-preserving patient data platforms.',
      expertise: ['healthcare', 'interoperability', 'fhir'],
    },
    {
      name: 'Ravi Menon',
      title: 'Principal Data Architect',
      organization: 'BlueOrbit Software',
      bio: 'Ravi designs high-throughput streaming architectures and mentors teams adopting event-driven patterns.',
      expertise: ['streaming', 'analytics', 'architecture'],
    },
    {
      name: 'Clara Bergström',
      title: 'Head of Sustainability',
      organization: 'Nordic Grid Alliance',
      bio: 'Clara advises utilities on renewable integration and carbon accounting for large events.',
      expertise: ['sustainability', 'energy'],
    },
  ],
};

/** Expo definitions; `offsetDays` keeps the demo always "current". */
const expos = [
  {
    key: 'tech',
    title: 'Global Tech Expo 2026',
    theme: 'Autonomous systems and the connected enterprise',
    category: 'technology',
    summary: 'Three days of robotics, edge computing and industrial software with 200+ exhibitors.',
    description:
      'Global Tech Expo brings together robotics vendors, industrial software companies and research groups. The programme covers collaborative robotics, edge AI, industrial IoT platforms and the operational realities of deploying automation at scale. Expect hands-on workshops, a startup zone and a dedicated recruiting floor.',
    offsetDays: { start: 14, end: 16, deadline: 11 },
    status: 'upcoming',
    isFeatured: true,
    maxAttendees: 6000,
    ticketPrice: 149,
    boothPriceFrom: 1200,
    tags: ['robotics', 'automation', 'iot', 'edge ai'],
    location: {
      venue: 'Metropolitan Convention Centre',
      hall: 'Hall A & B',
      address: '747 Howard Street',
      city: 'San Francisco',
      state: 'California',
      country: 'United States',
      postalCode: '94103',
      coordinates: { lat: 37.7842, lng: -122.4012 },
    },
    published: true,
  },
  {
    key: 'energy',
    title: 'Green Energy Summit 2026',
    theme: 'Grid resilience, storage and the electrification of everything',
    category: 'energy',
    summary: 'Utilities, storage vendors and policy makers meeting while the summit is live.',
    description:
      'The Green Energy Summit is a working summit: utility operators, storage manufacturers and regulators share deployment data on grid-scale batteries, virtual power plants and renewable integration. Sessions are streamed to partner hubs in Europe and Asia.',
    offsetDays: { start: -1, end: 2, deadline: -5 },
    status: 'ongoing',
    isFeatured: true,
    maxAttendees: 3500,
    ticketPrice: 0,
    boothPriceFrom: 900,
    tags: ['energy', 'storage', 'sustainability'],
    location: {
      venue: 'Nordic Congress Hall',
      hall: 'Summit Hall',
      address: 'Vasagatan 12',
      city: 'Stockholm',
      state: '',
      country: 'Sweden',
      postalCode: '111 20',
      coordinates: { lat: 59.3326, lng: 18.0649 },
    },
    published: true,
  },
  {
    key: 'health',
    title: 'Health Innovation Forum 2025',
    theme: 'Connected diagnostics and remote care',
    category: 'healthcare',
    summary: 'Completed forum on diagnostics interoperability and remote patient monitoring.',
    description:
      'Health Innovation Forum connected clinicians, device makers and regulators around remote monitoring, FHIR interoperability and the economics of virtual care. Recordings and slide decks remain available to registered attendees.',
    offsetDays: { start: -75, end: -73, deadline: -80 },
    status: 'completed',
    maxAttendees: 1800,
    ticketPrice: 99,
    boothPriceFrom: 700,
    tags: ['healthcare', 'diagnostics', 'telehealth'],
    location: {
      venue: 'Messe Berlin — Hall 4',
      hall: 'Hall 4',
      address: 'Messedamm 22',
      city: 'Berlin',
      state: '',
      country: 'Germany',
      postalCode: '14055',
      coordinates: { lat: 52.5049, lng: 13.2695 },
    },
    published: true,
  },
  {
    key: 'manufacturing',
    title: 'Smart Manufacturing Expo 2026',
    theme: 'Digital twins, quality automation and reshoring',
    category: 'manufacturing',
    summary: 'Draft programme — floor plan and sessions still being finalised.',
    description:
      'A draft programme for a manufacturing-focused expo covering digital twins, machine-vision quality control, and the operational case for reshoring production. Booths and sessions are being finalised with partners.',
    offsetDays: { start: 120, end: 122, deadline: 110 },
    status: 'draft',
    maxAttendees: 4000,
    ticketPrice: 120,
    boothPriceFrom: 1100,
    tags: ['manufacturing', 'digital twin', 'quality'],
    location: {
      venue: 'Hanover Fair Grounds',
      hall: 'Hall 6',
      address: 'Messegelände',
      city: 'Hanover',
      state: '',
      country: 'Germany',
      postalCode: '30521',
      coordinates: { lat: 52.3222, lng: 9.8078 },
    },
    published: false,
  },
];

/**
 * Session templates. `dayOffset` is relative to the expo start date, `hour`
 * places it in the day so demo reminders and "today" queries have data.
 */
const sessions = [
  {
    expoKey: 'tech',
    dayOffset: 0,
    startTime: '09:30',
    endTime: '10:30',
    title: 'Opening keynote: The autonomous enterprise in 2026',
    type: 'keynote',
    category: 'strategy',
    level: 'all',
    room: 'Hall A — Main Stage',
    capacity: 1200,
    isFeatured: true,
    description:
      'Where automation actually pays off this year: findings from 400 industrial deployments, the three bottlenecks that persist, and what the next 18 months of robotics investment looks like.',
    speakers: ['Dr. Nadia Petrova'],
    tags: ['robotics', 'strategy', 'automation'],
  },
  {
    expoKey: 'tech',
    dayOffset: 0,
    startTime: '11:15',
    endTime: '13:00',
    title: 'Hands-on workshop: Deploying a collaborative robot cell',
    type: 'workshop',
    category: 'robotics',
    level: 'intermediate',
    room: 'Workshop Lab 1',
    capacity: 40,
    description:
      'Bring a laptop. We programme a collaborative arm for a pick-and-place task, add vision-guided correction and validate cycle time against a simulated production target.',
    speakers: ['Dr. Nadia Petrova', 'Marcus Lee'],
    tags: ['workshop', 'cobot', 'hands-on'],
  },
  {
    expoKey: 'tech',
    dayOffset: 0,
    startTime: '14:00',
    endTime: '15:00',
    title: 'Panel: Edge AI in industrial environments',
    type: 'panel',
    category: 'technology',
    level: 'all',
    room: 'Hall B — Innovation Theatre',
    capacity: 300,
    description:
      'Hardware vendors and plant operators debate where inference belongs, how to keep models fresh, and how to prove ROI on edge deployments.',
    speakers: ['Ravi Menon', 'Samuel Osei'],
    tags: ['edge ai', 'panel', 'iot'],
  },
  {
    expoKey: 'tech',
    dayOffset: 1,
    startTime: '10:00',
    endTime: '11:00',
    title: 'Seminar: Industrial IoT gateways without the integration tax',
    type: 'seminar',
    category: 'iot',
    level: 'beginner',
    room: 'Hall A — Seminar Room 2',
    capacity: 150,
    description:
      'A pragmatic walkthrough of protocol translation, security hardening and fleet updates for industrial gateways, illustrated with three customer deployments.',
    speakers: ['Samuel Osei'],
    tags: ['iot', 'gateway', 'integration'],
  },
  {
    expoKey: 'tech',
    dayOffset: 1,
    startTime: '13:30',
    endTime: '15:00',
    title: 'Workshop: Machine-vision quality inspection on a budget',
    type: 'workshop',
    category: 'quality',
    level: 'intermediate',
    room: 'Workshop Lab 2',
    capacity: 35,
    description:
      'Build a defect-detection pipeline from a phone camera dataset, then review the failure modes that matter when the line runs at full speed.',
    speakers: ['Dr. Nadia Petrova'],
    tags: ['machine vision', 'quality', 'workshop'],
  },
  {
    expoKey: 'tech',
    dayOffset: 2,
    startTime: '11:00',
    endTime: '12:00',
    title: 'Presentation: Scaling a robotics fleet across 40 sites',
    type: 'presentation',
    category: 'operations',
    level: 'advanced',
    room: 'Hall B — Innovation Theatre',
    capacity: 250,
    description:
      'Operational lessons from rolling out autonomous mobile robots across 40 distribution sites: commissioning, exception handling and uptime economics.',
    speakers: ['Marcus Lee'],
    tags: ['amr', 'operations', 'scaling'],
  },
  {
    expoKey: 'energy',
    dayOffset: 0,
    startTime: '09:00',
    endTime: '10:00',
    title: 'Keynote: Grid resilience after the storage build-out',
    type: 'keynote',
    category: 'energy',
    level: 'all',
    room: 'Summit Hall — Stage 1',
    capacity: 900,
    isFeatured: true,
    description:
      'What two years of grid-scale battery deployment taught operators about resilience, market design and the limits of current interconnection queues.',
    speakers: ['Clara Bergström'],
    tags: ['energy', 'grid', 'storage'],
  },
  {
    expoKey: 'energy',
    dayOffset: 0,
    startTime: '11:30',
    endTime: '13:00',
    title: 'Workshop: Sizing a virtual power plant for a mid-size city',
    type: 'workshop',
    category: 'energy',
    level: 'intermediate',
    room: 'Workshop Room 3',
    capacity: 45,
    description:
      'Work through a real load profile, size storage and flexible demand, then stress-test the portfolio against a winter peak and a summer heatwave.',
    speakers: ['Clara Bergström', 'Samuel Osei'],
    tags: ['vpp', 'storage', 'workshop'],
  },
  {
    expoKey: 'energy',
    dayOffset: 1,
    startTime: '10:30',
    endTime: '11:30',
    title: 'Seminar: Wide-bandgap semiconductors in grid applications',
    type: 'seminar',
    category: 'electronics',
    level: 'advanced',
    room: 'Hall 2 — Seminar Stage',
    capacity: 180,
    description:
      'SiC and GaN device selection for inverters and chargers, including thermal design and qualification requirements for utility deployments.',
    speakers: ['Samuel Osei'],
    tags: ['semiconductors', 'power', 'energy'],
  },
  {
    expoKey: 'health',
    dayOffset: 0,
    startTime: '09:30',
    endTime: '10:30',
    title: 'Keynote: Interoperability as a clinical safety issue',
    type: 'keynote',
    category: 'healthcare',
    level: 'all',
    room: 'Hall 4 — Stage',
    capacity: 500,
    description:
      'When data moves between systems, patient safety depends on semantics, not just transport. Lessons from 22 hospital deployments.',
    speakers: ['Dr. Ingrid Hauser'],
    tags: ['healthcare', 'fhir', 'safety'],
  },
  {
    expoKey: 'health',
    dayOffset: 1,
    startTime: '11:00',
    endTime: '12:30',
    title: 'Workshop: Remote monitoring escalation design',
    type: 'workshop',
    category: 'telehealth',
    level: 'intermediate',
    room: 'Workshop Room B',
    capacity: 30,
    description:
      'Design escalation rules for a remote patient monitoring programme, then review alert fatigue metrics from a live deployment.',
    speakers: ['Dr. Ingrid Hauser'],
    tags: ['telehealth', 'monitoring', 'workshop'],
  },
];

const announcements = [
  {
    expoKey: 'energy',
    audience: 'all',
    priority: 'high',
    pinned: true,
    title: 'Shuttle service from Central Station every 10 minutes',
    body: 'Free shuttles run from Central Station (exit Vasagatan) to the Nordic Congress Hall every 10 minutes between 07:30 and 19:00. Last shuttle leaves the venue 45 minutes after the closing session.',
  },
  {
    expoKey: 'energy',
    audience: 'exhibitors',
    priority: 'normal',
    title: 'Exhibitor briefing moved to 08:15 tomorrow',
    body: 'Tomorrow morning’s exhibitor briefing now starts at 08:15 in Meeting Room 2 (level B). Coffee and pastries will be served from 08:00. Bring your booth checklist.',
  },
  {
    expoKey: 'tech',
    audience: 'attendees',
    priority: 'normal',
    title: 'Registration desks open 60 minutes before the keynote',
    body: 'Pick up your badge from the Hall A registration desks from 08:30 on day one. Bring the QR code from your Event Pass — express lanes are available for pre-registered attendees.',
  },
];

const feedbackSamples = [
  {
    category: 'session',
    subject: 'More hands-on workshop capacity please',
    message:
      'The collaborative robot workshop was excellent but filled within minutes. Could you run it twice next year, or add a second lab?',
    rating: 5,
  },
  {
    category: 'venue',
    subject: 'Signage for the D zone could be clearer',
    message: 'Found the D zone easily in the end, but the floor-plan signage near the cafeteria pointed the wrong way.',
    rating: 3,
  },
  {
    category: 'app',
    subject: 'QR check-in worked perfectly',
    message: 'Check-in took two seconds and the schedule notifications were genuinely useful. Great experience overall.',
    rating: 5,
  },
];

const tickets = [
  {
    subject: 'Invoice shows the wrong company name',
    description:
      'Our booth invoice for Green Energy Summit shows the trading name instead of the legal entity. We need a corrected invoice for our finance department.',
    category: 'payment',
    priority: 'high',
    status: 'in_progress',
    replies: [
      { staff: true, body: 'Thanks for flagging this — we have regenerated the invoice with your legal entity name. It will appear under Payments shortly.' },
    ],
  },
  {
    subject: 'Unable to upload our compliance certificate',
    description: 'The upload keeps failing for a 6 MB PDF. Is there a size limit for exhibitor documents?',
    category: 'technical',
    priority: 'medium',
    status: 'open',
    replies: [],
  },
];

module.exports = { DEMO_PASSWORD, users, expos, sessions, announcements, feedbackSamples, tickets, addDays, startOfDay };
